Completed Spring Boot Practice Task
VolandevlodD/book-store pull request #11
Opened 2024-05-21 09:19 UTC by VolandevlodD

- Added endpoints for shopping cart management:
  - GET `/api/cart` to retrieve user's shopping cart.
  - POST `/api/cart` to add a book to the shopping cart.
  - PUT `/api/cart/cart-items/{cartItemId}` to update the quantity of a book in the shopping cart.
  - DELETE `/api/cart/cart-items/{cartItemId}` to remove a book from the shopping cart.
- Created entities for shopping cart management:
  - ShoppingCart: Represents a user's shopping cart with fields: id, user, cartItems.
  - CartItem: Represents an item in a user's shopping cart with fields: id, shoppingCart, book, quantity.
- Implemented security requirements for users with role USER.
- Utilized Liquibase for database management.
- Integrated Pagination, Sorting, and Swagger to all controllers.

2024-05-22 02:44 UTC, azzilian requested changes
Splendid! Trivial thing to fix

2024-05-22 02:44 UTC, azzilian commented on src/main/java/org/example/bookstore/dto/cartitem/UpdateCartItemRequestDto.java
> +        @Min(1)
I would add message for those annotations

2024-05-23 08:13 UTC, karma-o requested changes
Looks good! left a few comments to think about

2024-05-23 08:13 UTC, karma-o commented on src/main/java/org/example/bookstore/controller/ShoppingCartController.java
> +    public CartItemDto updateCart(@RequestBody UpdateCartItemRequestDto requestDto,
same for other endpoints and their bodies
```suggestion
    public CartItemDto updateCart(@RequestBody @Valid UpdateCartItemRequestDto requestDto,
```

2024-05-23 08:13 UTC, karma-o commented on src/main/java/org/example/bookstore/model/CartItem.java
> +@Setter
let's not forget about equals & hashcode & toString, but exclude lazy initialized fields from them

2024-05-23 08:13 UTC, karma-o commented on src/main/java/org/example/bookstore/model/CartItem.java
> +    private Book book;
let's not leave them with fetch type eager by default and make them lazy

2024-05-23 08:13 UTC, karma-o commented on src/main/java/org/example/bookstore/service/impl/CartItemServiceImpl.java
> +    }
let's also check if that cart item belongs to the user who is logged in to be more secure

2024-05-24 10:29 UTC, yevheniisynytsia approved these changes

2024-05-24 10:49 UTC, merged