Implement JpaRepository, Liquibase, Soft Delete, and Additional Book Endpoints
VolandevlodD/book-store pull request #3
Opened 2024-04-26 14:54 UTC by VolandevlodD

1. **JpaRepository Implementation**: Replaced the existing `BookRepository` with a new one that uses the `JpaRepository` interface, providing out-of-the-box CRUD operations and query methods.

2. **Liquibase Support**: Added Liquibase support for database schema management, ensuring consistent and version-controlled database changes across environments.

3. **Hibernate DDL Auto Property**: Changed the value of `spring.jpa.hibernate.ddl-auto` property to `validate`, which will validate the schema against the entities at startup without making any changes to the database schema.

4. **Soft Delete Implementation**: Implemented soft delete functionality for the `Book` entity, allowing for logical deletion of books while retaining their data in the database.

5. **Additional Book Endpoints**: Added missing endpoints and methods to the `BookService` and `BookController`:

    - `PUT /api/books/{id}`: Updates a specific book with the provided request body.
      Example of request body:
      ```json
      {
        "title": "Updated Title",
        "author": "Updated Author",
        "isbn": "978-1234567890",
        "price": 19.99,
        "description": "Updated description",
        "coverImage": "https://example.com/updated-cover-image.jpg"
      }
      ```

    - `DELETE /api/books/{id}`: Soft deletes a specific book identified by its ID.

2024-04-27 17:26 UTC, Bohadan-Markatov approved these changes
lgtm

2024-04-29 10:48 UTC, yevheniisynytsia requested changes
Great job! Left some comments

2024-04-29 10:48 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/model/Book.java
> +    private boolean isDeleted = false;
move it lower please, make it the last field

2024-04-29 10:48 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
it is better to check if you have any book by id in your db at all

2024-04-29 10:48 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
you can create a private method for it and reuse it in `delete` as well

2024-04-29 10:48 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
```suggestion
```
primaryKey is not nullable by default

2024-04-29 10:48 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-isDeleted-column-to-book-entity.yaml
> +      id: add-isDeleted-column-to-book-entity
```suggestion
      id: add-is_deleted-column-to-books-table
```

2024-04-30 08:42 UTC, karma-o approved these changes
GJ! Just a couple moments that we should take a look at before mering

2024-04-30 08:42 UTC, karma-o commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +                "Book with %d not found".formatted(id)));
duplicated existence check
```suggestion
        checkIfBookExists(id);
```

2024-04-30 08:42 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                  type: varchar(255)
add new empty line at the end of files
```suggestion
                  type: varchar(255)
                  
```

2024-04-30 08:42 UTC, karma-o commented on src/main/resources/db/changelog/changes/02-add-isDeleted-column-to-book-entity.yaml
> +                    nullable: false
same here

2024-04-30 08:42 UTC, karma-o commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-add-isDeleted-column-to-book-entity.yaml
also, I'd rather combine these 2 files in 1 since both of them did not exist before that PR, but that is not that important - so up to you

2024-04-30 10:18 UTC, merged